// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSt8P0F3yu1OaPiSHY_jfbUaolycEdKOE',
    appId: '1:865066732248:web:d9f9d40d1bc9810ff5a5ad',
    messagingSenderId: '865066732248',
    projectId: 'aeternum-4ca15',
    authDomain: 'aeternum-4ca15.firebaseapp.com',
    storageBucket: 'aeternum-4ca15.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp5NyVZ5I6dF7wQNVR9DivCJ_QxDmJwYM',
    appId: '1:865066732248:android:15836d475120e323f5a5ad',
    messagingSenderId: '865066732248',
    projectId: 'aeternum-4ca15',
    storageBucket: 'aeternum-4ca15.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAf4EubI3n7JQsGcKAzhgEovrbAO6aggM',
    appId: '1:865066732248:ios:3953f1636569dc5af5a5ad',
    messagingSenderId: '865066732248',
    projectId: 'aeternum-4ca15',
    storageBucket: 'aeternum-4ca15.firebasestorage.app',
    iosBundleId: 'com.example.aeternumApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAf4EubI3n7JQsGcKAzhgEovrbAO6aggM',
    appId: '1:865066732248:ios:3953f1636569dc5af5a5ad',
    messagingSenderId: '865066732248',
    projectId: 'aeternum-4ca15',
    storageBucket: 'aeternum-4ca15.firebasestorage.app',
    iosBundleId: 'com.example.aeternumApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSt8P0F3yu1OaPiSHY_jfbUaolycEdKOE',
    appId: '1:865066732248:web:a4d8d0c84bb9f867f5a5ad',
    messagingSenderId: '865066732248',
    projectId: 'aeternum-4ca15',
    authDomain: 'aeternum-4ca15.firebaseapp.com',
    storageBucket: 'aeternum-4ca15.firebasestorage.app',
  );
}
